### ISSUE TITLE
Add image placeholders in the CvItem

### ISSUE THREAD

**Issue by hbarang** [hbarang/React-Cv-Template#5]
I was thinking about displaying images inside CvItems given a url or path in Data.json. When I tried it looked awful. If I have time to spare will look into it.

**Comment by alexeykravchenko9** [comment]
Hello, 
I'd like to take this issue, Could I take one?

**Comment by hbarang** [comment]
Sure , go ahead

**Comment by hbarang** [comment]
Resolved with #6 thanks to @alexeykravchenko9
