### ISSUE TITLE
Make CvItems dynamically loaded from Data.json

### ISSUE THREAD

**Issue by hbarang** [hbarang/React-Cv-Template#7]
Right now education, projects and experience CvItems are hardcoded in `index.js` we can do this dynamically by putting these in an array in the `Data.json` to make the code cleaner and more reusable. Should be easy, I'll look into it when I have time, anyone is welcome to work on this.

**Comment by christophercoppin** [comment]
Hello, if that's possible I'd like to take this one.

**Comment by hbarang** [comment]
Sure, thanks!

**Comment by hbarang** [comment]
Resolved with #8 by @christophercoppin
